export const data = [
    {   id: 1,
        word: "ฉัน",
        description: "",
    },
    {   id: 2,
        word: "เธอ",
        description: "",
    },
    {   id: 3,
        word: "คุณ",
        description: "",
    },
    {   id: 4,
        word: "ขอโทษ",
        description: "",
    },
    {   id: 5,
        word: "ขอบคุณ",
        description: "",
    },
    {   id: 6,
        word: "โกรธ",
        description: "",
    },
    {   id: 7,
        word: "ชอบ",
        description: "",
    },
    {   id: 8,
        word: "ไม่ชอบ",
        description: "",
    },
    {   id: 9,
        word: "คิดถึง",
        description: "",
    },
    {   id: 10,
        word: "ง่วง",
        description: "",
    },
    {   id: 11,
        word: "กลัว",
        description: "",
    },
    {   id: 12,
        word: "เศร้า",
        description: "",
    },
    {   id: 13,
        word: "สนุก",
        description: "",
    },
    {   id: 14,
        word: "เหนื่อย",
        description: "",
    },
    {   id: 15,
        word: "สวย",
        description: "",
    },
    {   id: 16,
        word: "สวัสดี",
        description: "",
    },
    {   id: 17,
        word: "ขอบคุณ",
        description: "",
    },
    {   id: 18,
        word: "ช่วยด้วย",
        description: "",
    },
    {   id: 19,
        word: "เข้าใจ",
        description: "",
    },
    {   id: 20,
        word: "เกรงใจ",
        description: "",
    },
    {   id: 21,
        word: "โกหก",
        description: "",
    },
    {   id: 22,
        word: "ไม่ได้โกหก",
        description: "",
    },
    {   id: 23,
        word: "สนิทกัน",
        description: "",
    },
    {   id: 24,
        word: "ดีกัน",
        description: "",
    },
    {   id: 25,
        word: "อร่อย",
        description: "",
    },
    {   id: 26,
        word: "ไม่อร่อย",
        description: "",
    },
    {   id: 27,
        word: "หิว",
        description: "",
    },
    {   id: 28,
        word: "อิ่ม",
        description: "",
    },
    {   id: 29,
        word: "ใจเย็น",
        description: "",
    },
    {   id: 30,
        word: "ตื่นเต้น",
        description: "",
    },
    {   id: 31,
        word: "ไม่สบาย",
        description: "",
    },
    {   id: 32,
        word: "สบายดี",
        description: "",
    },
    {   id: 33,
        word: "เหงา",
        description: "",
    },
    {   id: 34,
        word: "อะไร",
        description: "",
    },
    {   id: 35,
        word: "ทำไม",
        description: "",
    },
    {   id: 36,
        word: "ที่ไหน",
        description: "",
    },
    {   id: 37,
        word: "เท่าไหร่",
        description: "",
    },
    {   id: 38,
        word: "ใช่",
        description: "",
    },
    {   id: 39,
        word: "ไม่ใช่",
        description: "",
    },
    {   id: 40,
        word: "วันนี้",
        description: "",
    },
    {   id: 41,
        word: "ทุกวัน",
        description: "",
    },
    {   id: 42,
        word: "เมื่อวาน",
        description: "",
    },
    {   id: 43,
        word: "อยาก",
        description: "",
    },
    {   id: 44,
        word: "ไม่อยาก",
        description: "",
    },
    {   id: 45,
        word: "ใคร",
        description: "",
    },
    {   id: 46,
        word: "ชื่อ",
        description: "",
    },
    {   id: 47,
        word: "บอก",
        description: "",
    },
    {   id: 48,
        word: "หัวเราะ",
        description: "",
    },
    {   id: 49,
        word: "ขอ",
        description: "",
    },
    {   id: 50,
        word: "พบกันใหม่",
        description: "",
    }
]

